# {{title}} — Pi runtime

Pi appends this file to the project system prompt, so it is the one Pi reads —
the name is the contract, not a convention. This workspace is a deterministic
projection of the `.claude/` SSOT, generated by `papersmith` {{version}}.

Read `papersmith.yaml`, `guidance/paper-guide/`, and the applicable
`skills/*/SKILL.md` before working on the paper.

## Agents

{{agents}}

## Skills

Every top-level skill under `skills/` is also generated as a Pi prompt template
in `.pi/prompts/<name>.md`, so it can be invoked as `/<name>`. Each template
loads that skill's `SKILL.md` and passes your text through as `$ARGUMENTS`. The
directory is a framework artifact that `papersmith upgrade` restores, so do not
edit it by hand.

## Precedence

A trusted project `.pi/APPEND_SYSTEM.md` takes precedence over the operator's
own `~/.pi/agent/APPEND_SYSTEM.md`, and the two are never combined: this file
therefore replaces that append inside this workspace rather than adding to it.
